from .Zho_Selector import NODE_CLASS_MAPPINGS  as NODE_CLASS_MAPPINGS_SELECTOR
from .Zho_Standard__new import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_ZHO
from .Zho_Standard__new_EN import NODE_CLASS_MAPPINGS  as NODE_CLASS_MAPPINGS_EN

# Combine the dictionaries
NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS_SELECTOR, **NODE_CLASS_MAPPINGS_ZHO, **NODE_CLASS_MAPPINGS_EN}

__all__ = ['NODE_CLASS_MAPPINGS']
